/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;

import org.example.assembler.Assembler;

public class HackAssembler {

    public static void main(String[] args) throws IOException {
        String asmFilePath = args[0];

        Assembler assembler = new Assembler(asmFilePath);
        assembler.assemble();
    }
}
